# Generated by Django 5.0.7 on 2024-07-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='institution_number',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='swift_code',
        ),
        migrations.AddField(
            model_name='bank',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='branch',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='branch',
            name='transit_number',
            field=models.CharField(max_length=20),
        ),
    ]
